# action.yml
name: "Akash on Github Actions Update Deploy"
description: "Update a deployment on Akash with a deploy.yml"
inputs:
  AKASH_DSEQ: # id of input
    description: "deployment sequence id"
    required: true
  AKASH_PROVIDER: # id of input
    description: "provider address to send update to"
    required: true
  SDL_PATH: # id of input
    description: "sdl file to target for deployment"
    required: false
    default: "deploy.yaml"
  AKASH_NODE: # id of input
    description: "rpc node to use for commands"
    required: false
    default: "http://135.181.181.121:28957"
runs:
  using: "composite"
  steps:
    - name: import key
      shell: bash
      env:
        AKASH_HOME: /home/runner/.akash
      run: |-
        provider-services tx deployment update ${{inputs.SDL_PATH}} --dseq ${{inputs.AKASH_DSEQ}} --chain-id akashnet-2 --from AKASH_GITHUB_RUNNER --keyring-backend test --node ${{inputs.AKASH_NODE}} -y
    - name: Sleep before sending update
      shell: bash
      run: sleep 15s
    - name: send update deployment
      shell: bash
      env:
        AKASH_HOME: /home/runner/.akash
      run: |-
        provider-services send-manifest ${{inputs.SDL_PATH}} --node ${{inputs.AKASH_NODE}} --from AKASH_GITHUB_RUNNER --keyring-backend test --provider ${{inputs.AKASH_PROVIDER}} --dseq ${{inputs.AKASH_DSEQ}}
